services:
  node-backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - ml
    networks:
      - ending_project
    restart: always

  ml:
    build: ./ml
    ports:
      - "8001:5000"
    depends_on:
      - db
    networks:
      - ending_project
    restart: always

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: galvaniz
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./database/db_data:/var/lib/mysql
      - ./database/db_data:/docker-entrypoint-initdb.d
    networks:
      - ending_project
    restart: always

volumes:
  db_data:

networks:
  ending_project:
    driver: bridge
